version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  web:
    image: nginx:latest
    volumes:
      - ../public:/usr/share/nginx/html # Map the local html directory to the container's default location for nginx
      # Uncomment the following line if you want to use a custom nginx.conf
      # - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
